apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
type: Opaque
stringData:
  username: {{ .Values.postgresql.auth.username }}
  password: {{ .Values.postgresql.auth.password }}
  database: {{ .Values.postgresql.auth.database }}